version: "3.6"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    ports:
      - 8080:8080
    links:
      - redis:redis
    networks:
      main:
        aliases:
          - php
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:4.0-alpine
    networks:
      main:
        aliases:
          - redis

networks:
  main: